# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package manifest and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies; devDependencies are needed for building
RUN npm install --ignore-scripts

# Copy the rest of the files
COPY . .

# Build the project using tsc
RUN npx tsc && \
    cp build/mcp-adjust.js build/index.js && \
    chmod 755 build/index.js

# Set environment variable for Adjust API key
ENV ADJUST_API_KEY=123456

# Define the CMD to run the MCP server using the Adjust API key
CMD ["node", "build/mcp-adjust.js", "${ADJUST_API_KEY}"]
